name: Kadek Palgunadi's Blog
description: Blogging about stuffs that I concern about
meta_description: "My sharing knowledge pages, Blogging about stuffs"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'localhost:4000'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]
github_username: palgunadi1993

# Details for the RSS feed generator
url:            "https://palgunadi1993.github.io"
author:         'Kadek Hendrawan Palgunadi'
